const char PAGE_HTML[] PROGMEM = "<!DOCTYPE html>\n"
"<head>\n"
"<title>WEB Page</title>\n"
"<meta charset=\"UTF-8\"/>\n"
"</head>\n"
"<script>\n"
"  var ws;\n"
"  function openSocket(){\n"
"	var ws = new WebSocket(\"ws://192.168.4.1:80/websocket\")\n"
"   ws.onopen = function(){\n"
"		console.log(\"WebSocket Connected !!!\");\n"
"		//ws.send(String.fromCharCode(13) + String.fromCharCode(10));\n"
"   };\n"
"	ws.onmessage = function(evt){\n"
"		console.log(evt.data);\n"
"	};\n"
"   ws.onclose = function(){console.log(\"WebSocket Clooooosed !!!\");};\n"
"  }\n"
"  function closeSocket(){\n"
"	ws.close();"
"  }\n"
"  function sendData(){\n"
"	var message = \"\";\n"
"	message += \"Enter sendData function\";\n"
"	document.getElementById(\"debug\").innerHTML = message;\n"
"\n"
"	var request = new XMLHttpRequest();\n"
"	request.overrideMimeType(\"text/plain\")\n"
"	document.getElementById(\"debug\").innerHTML = message;\n"
"\n"
"	request.onreadystatechange = function(){\n"
"		message += \"Enter send function\";\n"
"		if(this.readyState == 4 && this.status == 200){\n"
"			var reponse = this.responseText;\n"
"   			document.getElementById(\"textBox\").innerHTML = reponse;\n"
"		}\n"
"	};\n"
"	document.getElementById(\"debug\").innerHTML = message;\n"
"	request.open(\"GET\", \"http://192.168.4.1:80/data\", true);\n"
"	request.send();\n"
"	\n"
"  }\n"
"\n"
"</script>\n"
"<body>\n"
"<h3>Module de commande ESP8266</h3>\n"
"<button type=\"button\" onclick=\"sendData()\">Send Data</button>\n"
"<button type=\"button\" onclick=\"openSocket()\">Open Socket</button>\n"
"<button type=\"button\" onclick=\"closeSocket()\">Close Socket</button>\n"
"<div id=\"textBox\"></div>\n"
"<div id=\"debug\"></div>\n"
"</body>\n"
"</html>\n"
;
